version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: CsvHelper
    versions:
    - 21.3.1
    - 22.1.0
    - 22.1.1
    - 22.1.2
    - 23.0.0
    - 24.0.0
    - 24.0.1
    - 25.0.0
    - 26.0.0
    - 26.0.1
    - 26.1.0
    - 27.0.1
  - dependency-name: Costura.Fody
    versions:
    - 5.0.2
    - 5.1.0
    - 5.2.0
  - dependency-name: Fody
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
- package-ecosystem: nuget
  directory: "/EloSwiss.Tests"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: CsvHelper
    versions:
    - 21.3.1
    - 22.1.0
    - 22.1.1
    - 22.1.2
    - 23.0.0
    - 24.0.0
    - 24.0.1
    - 25.0.0
    - 26.0.0
    - 26.0.1
    - 26.1.0
    - 27.0.1
  - dependency-name: Costura.Fody
    versions:
    - 5.0.2
    - 5.1.0
    - 5.2.0
  - dependency-name: Fody
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
- package-ecosystem: nuget
  directory: "/EloSwissCli"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: CsvHelper
    versions:
    - 21.3.1
    - 22.1.0
    - 22.1.1
    - 22.1.2
    - 23.0.0
    - 24.0.0
    - 24.0.1
    - 25.0.0
    - 26.0.0
    - 26.0.1
    - 26.1.0
    - 27.0.1
  - dependency-name: Costura.Fody
    versions:
    - 5.0.2
    - 5.1.0
    - 5.2.0
  - dependency-name: Fody
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
- package-ecosystem: nuget
  directory: "/EloSwiss"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
